/**
 * Solar savings estimate — shared calculation.
 *
 * Single source of truth for the on-site TEASER numbers (home intake +, next,
 * the /solar-calculator tool). The full, personalised estimate that the
 * homeowner receives by email is generated by AISolar's lead_intake agent after
 * the lead lands; this on-site figure is a fast, honest teaser only.
 *
 * NOTE: QuickSavingsCalculator.tsx still carries its own copy of this maths;
 * when /solar-calculator is gated it should be refactored to import from here so
 * there is one formula. Keep the two in sync until then.
 */
import { SOLAR_DATA } from '@/lib/solar-data';

const UNIT_RATE = 0.34; // €/kWh average incl. VAT across providers
const STANDING_CHARGE_ANNUAL = 200; // €/year
const GENERATION_PER_KWP = 1000; // kWh/kWp/yr, well-optimised south-facing Irish roof
const COST_PER_KWP = 1600; // €/kWp installed
const BASE_INSTALL_COST = 1800; // fixed costs (scaffolding, design, commissioning)
const CEG_RATE = SOLAR_DATA.export.ratePerKwh; // Clean Export Guarantee €/kWh
const SEAI_GRANT = SOLAR_DATA.grant.amount; // €1,800

export const HOME_TYPES = [
  { id: 'apartment', label: 'Apartment / Terrace', minKwp: 1.5, maxKwp: 9.7 },
  { id: 'semi', label: 'Semi-Detached', minKwp: 2.5, maxKwp: 9.7 },
  { id: 'detached', label: 'Detached', minKwp: 3, maxKwp: 9.7 },
] as const;

export interface EstimateResult {
  annualBill: number;
  systemSizeKwp: number;
  totalAnnualBenefit: number;
  monthlySavings: number;
  billReductionPct: number;
  paybackYears: number;
  total25yrSavings: number;
}

/** Fast teaser estimate from a monthly bill + home type. */
export function estimateSavings(monthlyBill: number, homeId: string): EstimateResult {
  const home = HOME_TYPES.find((h) => h.id === homeId) || HOME_TYPES[1];
  const annualBill = monthlyBill * 12;

  const energyCost = Math.max(annualBill - STANDING_CHARGE_ANNUAL, 100);
  const annualUsage = Math.round(energyCost / UNIT_RATE);

  const targetGeneration = annualUsage * 0.85;
  let idealKwp = targetGeneration / GENERATION_PER_KWP;
  idealKwp = Math.round(idealKwp * 2) / 2;
  const systemSizeKwp = Math.max(home.minKwp, Math.min(idealKwp, home.maxKwp));

  const annualGeneration = Math.round(systemSizeKwp * GENERATION_PER_KWP);

  const sizeRatio = annualUsage / Math.max(annualUsage + annualGeneration, 1);
  const selfConsumptionRatio = Math.min(0.8, 0.48 + 0.38 * sizeRatio);

  const selfConsumedKwh = Math.round(annualGeneration * selfConsumptionRatio);
  const exportedKwh = annualGeneration - selfConsumedKwh;

  const annualSavingFromSelfUse = Math.round(selfConsumedKwh * UNIT_RATE);
  const annualExportEarnings = Math.round(exportedKwh * CEG_RATE);
  const totalAnnualBenefit = annualSavingFromSelfUse + annualExportEarnings;

  const annualBillAfterSolar = Math.max(annualBill - totalAnnualBenefit, STANDING_CHARGE_ANNUAL);
  const monthlySavings = Math.round(((annualBill - annualBillAfterSolar) / 12) * 100) / 100;
  const billReductionPct = Math.round((totalAnnualBenefit / annualBill) * 100);

  const installCost = Math.round(systemSizeKwp * COST_PER_KWP + BASE_INSTALL_COST);
  const costAfterGrant = installCost - SEAI_GRANT;
  const paybackYears = Math.max(Math.round((costAfterGrant / totalAnnualBenefit) * 10) / 10, 4);

  let total25yrSavings = 0;
  let yearlyGen = annualGeneration;
  let currentUnitRate = UNIT_RATE;
  for (let yr = 1; yr <= 25; yr++) {
    const self = Math.min(yearlyGen * selfConsumptionRatio, annualUsage * selfConsumptionRatio);
    const exp = yearlyGen - self;
    total25yrSavings += Math.round(self * currentUnitRate + exp * CEG_RATE);
    yearlyGen *= 0.995; // 0.5% annual degradation
    currentUnitRate *= 1.03; // 3% annual price rise
  }

  return {
    annualBill,
    systemSizeKwp,
    totalAnnualBenefit,
    monthlySavings,
    billReductionPct,
    paybackYears,
    total25yrSavings,
  };
}

export function fmtEur(n: number): string {
  return '€' + Math.round(n).toLocaleString();
}
