module.exports = {
  apps: [
    {
      name: 'solar-ireland',
      script: 'npx',
      args: 'next start -p 3001 -H 0.0.0.0',
      cwd: '/home/z/my-project',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '900M',
      env: {
        NODE_ENV: 'production',
        NODE_OPTIONS: '--max-old-space-size=1024',
        PORT: 3001,
      },
      error_file: '/home/z/my-project/logs/pm2-error.log',
      out_file: '/home/z/my-project/logs/pm2-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      restart_delay: 3000,
      max_restarts: 100,
      min_uptime: '10s',
      kill_timeout: 5000,
    },
    {
      name: 'solar-proxy',
      script: '_proxy-server.js',
      cwd: '/home/z/my-project',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '100M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/home/z/my-project/logs/proxy-error.log',
      out_file: '/home/z/my-project/logs/proxy-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      restart_delay: 2000,
      max_restarts: 100,
      min_uptime: '5s',
      kill_timeout: 3000,
    },
  ],
};
