var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e683c88a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b9a0874._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_3941aac0.js")
R.c("server/chunks/ssr/[root-of-the-server]__8a0264b0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_bc6b8ddf._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1690ee0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_9bea2a37._.js")
R.c("server/chunks/ssr/[root-of-the-server]__05fe45fb._.js")
R.c("server/chunks/ssr/src_app_loading_tsx_7fa31b7f._.js")
R.c("server/chunks/ssr/_61b58078._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_554ec2bf.js")
R.m(84878)
module.exports=R.m(84878).exports
