var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/portal/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1b97bae2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b9a0874._.js")
R.c("server/chunks/ssr/_9a3054e3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__bdb6efdd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_bc6b8ddf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_9bea2a37._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1690ee0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__05fe45fb._.js")
R.c("server/chunks/ssr/src_app_loading_tsx_7fa31b7f._.js")
R.c("server/chunks/ssr/_61b58078._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_portal_loading_tsx_316ff80b._.js")
R.c("server/chunks/ssr/_next-internal_server_app_portal_page_actions_245a7fa2.js")
R.m(82774)
module.exports=R.m(82774).exports
